# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x = s.split()
print (x)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of{} is kilometers.".format(planet,diameter))

The diameter ofEarth is kilometers.

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d={
    'k1':[1,2,3,{
        'tricky':['oh','man','inception',{
            'target':[1,2,3,'hello']
        }]
    }]
}

# Numpy

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,4,5])

In [ ]:
import numpy

In [ ]:
np=numpy

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.21.6

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
arr = np.zeros(shape=(3,2))
pan = pd.DataFrame(arr)
pan

     0    1
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
print("jan,2022")
print(np.arange('2023-01', '2023-03', dtype ='datetime64[D]')[:41])

jan,2022
['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31' '2023-02-01' '2023-02-02' '2023-02-03' '2023-02-04'
 '2023-02-05' '2023-02-06' '2023-02-07' '2023-02-08' '2023-02-09'
 '2023-02-10']

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
pd.DataFrame(lists)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24